#!/bin/bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD

time java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar ../prebuilt/gatk.jar HaplotypeCaller --native-pair-hmm-threads 16 -R ./input/fasta/E.coli_K12_MG1655.fa -I E_coli_K12.sorted.markdup.bam -O E_coli_K12.g.vcf
